### ISSUE TITLE
Animation: Optimize animation runner to run same animations from same function

### ISSUE THREAD

**Issue by chrfalch** [fram-x/react-native-fluid#13]
When setting up multiple animations, we might have animations with the same duration, offset and easing. They should be played by the same animation function.

**Comment by chrfalch** [comment]
Tested out but a solution was not found. We are creating approx 27 nodes for a single interpolation, basically just `callFunc` and `param` nodes. Might have a look and see if we can reduce this some.

**Comment by terrysahaidak** [comment]
What about real native nodes, something similar to [this](https://github.com/kmagiera/react-native-reanimated/pull/458) approach?

**Comment by chrfalch** [comment]
Nice approach! The issue mentioned in here is basically about animation nodes that are created based on animation declarations - so they will not be available at compile time. But the idea is great!

Each animation in fluid transition (where 1 meaning one style or property value animation) emits 27 nodes, I addition the new timing function emits 20 nodes only.

**Comment by terrysahaidak** [comment]
Are there any common patterns?

**Comment by chrfalch** [comment]
Maybe it could be a good idea to run this on some of the proc nodes?
